# Generated by Django 4.2.2 on 2023-06-11 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_total_alter_order_total_proce'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_proce',
            new_name='total_price',
        ),
    ]
